# For values quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create values GET request with or without query parameters;
# * 'ptr' and 'ptrp' create values POST request with values simple or parameter-like body;
# * 'mptr' and 'fptr' create values POST request to submit values form with values text or file field (multipart/form-data);
GET http://localhost:8081/ping
Accept: application/json

###

GET http://localhost:8081/pppp
Accept: application/json

###

GET http://localhost:8081/echo?input=jallaballa
Accept: application/json

###

GET http://localhost:8081/asset/test.txt
Accept: text/plain

###